
echo "CREATE USER IF NOT EXISTS '$DB_PIPELINE_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$DB_PIPELINE_PASSWORD';"
echo "GRANT CREATE, ALTER, DROP, REFERENCES, INDEX, SELECT, INSERT, UPDATE ON *.* TO '$DB_PIPELINE_USER'@'%';"

echo "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
echo "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$DB_PASSWORD';"
echo "GRANT SELECT, INSERT, UPDATE, DELETE ON $DB_NAME.* TO '$DB_USER'@'%';"
